# Generated by Django 6.0.2 on 2026-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=20)),
                ('Emp_name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
            ],
        ),
    ]
