# Generated by Django 6.0.2 on 2026-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cadence_id', models.CharField(max_length=10)),
                ('name', models.TextField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
    ]
